<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>SimHub.Plugin.Voicemeeter</RootNamespace>
    <AssemblyName>SimHub.Plugin.Voicemeeter</AssemblyName>
    <Platforms>AnyCPU</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="GameReaderCommon">
      <HintPath>$(SIMHUB_INSTALL_PATH)GameReaderCommon.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(SIMHUB_INSTALL_PATH)log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SimHub.Logging, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(SIMHUB_INSTALL_PATH)SimHub.Logging.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SimHub.Plugins">
      <HintPath>$(SIMHUB_INSTALL_PATH)SimHub.Plugins.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>

  <Target Name="CopyToSimHub" AfterTargets="Build">
    <ItemGroup>
      <SimHubOutputFiles Include="$(TargetDir)$(TargetName).dll;$(TargetDir)$(TargetName).pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(SimHubOutputFiles)" DestinationFolder="$(SIMHUB_INSTALL_PATH)" SkipUnchangedFiles="false" />
  </Target>

</Project>
